# This is a basic workflow to help you get started with Actions

name: Update our SLOs 

# Controls when the action will run. 
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest 
    container: 
      image: nadermor77/nobl9_github:77
      env:
        GITHUB_RUNNER_HOME: /root
   #   credentials:
   #     username: ${{ secrets.DOCKER_USERNAME }}
   #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      ports:
        - 80 
    steps:
      - uses: actions/checkout@v2
      - name: nobl9 slo yaml file
        run: |
          echo "Adding Contexts to the config"
          printf "%s\n%s\n%s\n%s\ny\n" "test" "${{ secrets.SLO_CTL_CLIENTID }}" "${{ secrets.SLO_CTL_CLIENTSECRET }}" "" | sloctl add-context
          echo "Checking the config file"
          cat ~/.config/nobl9/config.toml
          echo "Running sloctl"\n
          echo "Creating Dragon GO latency"\n
          sloctl apply -f ~/slo/slo.yml
